# Generated by Django 4.0.4 on 2022-07-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_alter_meals_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='meals',
            options={'verbose_name': 'Meal', 'verbose_name_plural': 'Meals'},
        ),
    ]
