# Generated by Django 4.0.4 on 2022-08-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedetails',
            name='phone',
            field=models.CharField(default='0933872949', max_length=225),
        ),
    ]
